### ISSUE TITLE
Container graphql-django-redis-1 starting forever.

### ISSUE THREAD

**Issue by lpesado-santex** [MikeSoft/GraphQL-Django#1]
When I run `make buildandrun` as stated in the readme, I got the error:

```
docker-compose down
docker volume rm bloomtalent_web-django bloomtalent_db-data bloomtalent_redisdata
Error: No such volume: bloomtalent_web-django
Error: No such volume: bloomtalent_db-data
Error: No such volume: bloomtalent_redisdata
make: *** [Makefile:4: buildandrun] Error 1
```

So I comented line 4 on the Makefile, but i left it an hour and  Container graphql-django-redis-1 keeps in starting state.
Any suggestions?

![image](https://github.com/MikeSoft/GraphQL-Django/assets/112591305/13b2db9a-1ead-496d-8d63-5bcb40b8bb65)

**Comment by lpesado-santex** [comment]
@MikeSoft

**Comment by MikeSoft** [comment]
Sorry , I solved it before of reading this issue. 
I solved it in this commit: https://github.com/MikeSoft/GraphQL-Django/commit/3e122a0dafe9e10d031d988b92578fb3d7664773

this happened because in the make file,  I assumed that the name of the volumes were invariant when there are created. 
Anyway , the good practice to remove the volumes and containers is with the command `docker-compose down -v` , which is the command i've implemented in the Makefile.

**Comment by lpesado-santex** [comment]
awesome, thanks!

**Comment by lpesado-santex** [comment]
Sorry @MikeSoft , still with the same issue. I mean, once I commented the line (the one you remove) I was getting this error

![image](https://github.com/MikeSoft/GraphQL-Django/assets/112591305/0b46b2ca-04c2-4321-bc30-f15df180f019)

Here are the version i have
➜  ~ docker-compose -v
Docker Compose version v2.18.1
➜  ~ docker -v
Docker version 20.10.13, build a224086

Anywway I have another channel using a similar config, with redis image and is working. Also:
```
➜  ~ sudo docker pull redis
[sudo] password for lupesado: 
Using default tag: latest
latest: Pulling from library/redis
Digest: sha256:3f10f8fc884547e425ec7a39080e6a4e371772b9ffd093919773531a8b4e4ff1
Status: Image is up to date for redis:latest
docker.io/library/redis:latest

```
